spring:
  application:
    name: wlcp-metrics
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:liquibase/changelogs/liquibase-parent-changelog.xml
    default-schema: ${DB_SCHEMA}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
server:
   port: 8084
eureka:
   client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
   instance:    prefer-ip-address: true
    ip-address: ${ECS_INSTANCE_IP_ADDRESS}